var app=angular.module('myapp1',['ui.router','ui.bootstrap','angularFileUpload']);
	app.config(function($stateProvider,$urlRouterProvider){
		$urlRouterProvider.when('','/logins');//默认页面定向到'/logins'
		$stateProvider
		.state('logins',{
			url:'/logins',
			templateUrl:'logins.html',
		})
		.state('homepage',{
			url:'/homepage',
			templateUrl:'homepage.html'
		})
		.state('homepage.Article',{
			url:'/Article?page&size&type&status&startAt&endAt',
			templateUrl:'Article.html'
		})
		.state('homepage.articleAdd',{
			url:'/articleAdd?id',
			templateUrl:'articleAdd.html'
		})
	});